name: CI
on: [push, pull_request]
permissions:
  contents: read
  id-token: write
  pages: write
jobs:
  ci:
    uses: york-fs/monorepo/.github/workflows/kicad.yml@c99482853eda99f120c14326403cf6cb4e41cdb9
